# -*- coding: utf-8 -*-

"""
Anki Add-on: Review Heatmap

Module-level entry point for the add-on into Anki 2.0.x/2.1.x

Please do not edit this file if you are not sure what you are doing.

Copyright: (c) 2016-2018 Glutanimate <https://glutanimate.com/>
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl.html>
"""

from ._version import __version__  # noqa: F401

from . import main  # noqa: F401
